config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boasts do
    member do
      put "like", to: "boasts#upvote"
    end
  end

  resources :users do
    resources :categories do
      resources :boasts
    end
  end

  root "boasts#index"

end

app/models/boast.rb
class Boast < ActiveRecord::Base
  acts_as_votable
  scope :category, -> category { where(:category => category) }
  belongs_to :user
  belongs_to :category

  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_many :boasts
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  scope :category, -> category { where(:category => category) }
  belongs_to :user
  belongs_to :category

  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, uniqueness: true, presence: true
  has_many :boasts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
  end
end

app/controllers/boasts_controller.rb
class BoastsController < ApplicationController
  before_action :find_boast, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  has_scope :category

  def index
    @boasts = Boast.all.order("created_at DESC")
    if user_signed_in?
      @user = current_user.id
    end
  end

  def show
  end

  def new
    @boast = current_user.boasts.build
  end

  def create
    unlocked_params = ActiveSupport::HashWithIndifferentAccess.new(boast_params)
    @boast = current_user.boasts.build(unlocked_params)
    if @boast.save
      redirect_to @boast, notice: "Successfully created new Boast"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    unlocked_params = ActiveSupport::HashWithIndifferentAccess.new(boast_params)
    if @boast.update(unlocked_params)
      redirect_to @boast, notice: "Boast was successfuly updated"
    else
      render 'edit'
    end
  end

  def destroy
    @boast.destroy
    redirect_to root_path
  end

  def upvote
    @boast.upvote_by current_user
    redirect_to :back
  end

  def category
    @boasts = apply_scopes(Boast).all.order("created_at DESC")
    render 'category/show'
  end

  private

  def boast_params
    boast_params_hash = params[:boast]
    boast_params_hash[:category_id] = Category.find_or_create_by(name: params[:boast][:category]).id
    boast_params_hash.delete(:category)
    boast_params_hash
  end

  def find_boast
    @boast = Boast.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
  end

  def show
    @user = User.find(params[:user_id])
    @category = Category.find(params[:id])
    @boasts = Boast.where(user_id: @user.id, category_id: @category.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @boasts = Boast.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boasts_helper.rb
module BoastsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/boasts/_form.html.haml
= simple_form_for @boast, html: { multipart: true} do |f|
  - if @boast.errors.any?
    #errors
      %h2
      = pluralize(@boast.errors.count, "error")
      prevented this Boast from saving
      %ul
        - @boast.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.input :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :category, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }
  = f.button :submit, class: "btn btn-primary"

app/views/boasts/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Your Boast
      .panel-body
        .current_image
          %strong.center Current Image
          = image_tag @boast.image.url(:medium)
        = render 'form'

app/views/boasts/index.html.haml
#boasts.transitions-enabled
  - @boasts.each do |boast|
    .box.panel.panel-default
      = link_to (image_tag boast.image.url), boast
      .panel-body
        %h1= link_to boast.title, boast
        %h6= link_to boast.category.name, user_category_url(boast.user_id, boast.category_id)
        %p.user
          Submitted by
          = boast.user.username

app/views/boasts/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Boast
      .panel-body
        = render 'form'

app/views/boasts/show.html.haml
#boast_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.boast_image
        = image_tag @boast.image.url
      .panel-body
        %h1= @boast.title
        %br
        %br
        %p.description= @boast.description
      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by:
            %i= @boast.user.username
            to
            %br
            %b= link_to @boast.category.name, user_category_url(@boast.user_id, @boast.category_id)
          .col-md-6
            .btn-group.pull-right
              = link_to like_boast_path(@boast), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-thumbs-up
                  = @boast.get_upvotes.size
              - if user_signed_in? && @boast.user_id == current_user.id
                = link_to "Edit", edit_boast_path, class: "btn btn-default"
                = link_to "Delete", boast_path, method: :delete, data: { confirm: "Are you sure you want to delete this boast?"}, class: "btn btn-default"

app/views/categories/show.html.haml
.category-show
  %h1= @category.name
  %h4
    %i= @user.username
#boasts.transitions-enabled
  - @boasts.each do |boast|
    .box.panel.panel-default
      = link_to (image_tag boast.image.url), boast
      .panel-body
        %h2= link_to boast.title, boast

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Boast It
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .wrapper
        .clip-text.clip-text_two.hit-the-floor Boast It
      / .hit-the-floor Boast It

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          %li= link_to "New Boast", new_boast_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Your Boasts", user_path(current_user.id)
          %li= link_to "Log Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          %li= link_to "Register New Account", new_user_registration_path
          %li= link_to "Log In", new_user_session_path
      %h4 Go on, show off
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield
    .panel-footer
      %ul.nav.navbar-right
        %li= link_to "About", new_user_session_path

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true} do |f|
  - if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.input :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :category, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }
  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Your Pin
      .panel-body
        .current_image
          %strong.center Current Image
          = image_tag @pin.image.url(:medium)
        = render 'form'

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.pabel-default
      .panel-heading
        %h1 New Pin
      .panel-body
        = render 'form'

app/views/users/show.html.haml
#boasts.transitions-enabled
  - @boasts.each do |boast|
    .box.panel.panel-default
      = link_to (image_tag boast.image.url), boast
      .panel-body
        %h1= link_to boast.title, boast
        %h6= link_to boast.category.name, user_category_url(boast.user_id, boast.category_id)